version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
artifacts:
  files:
    - ./*
    - ./**/**

  # Vue directory
  base-directory: dist
